package capros;

/* The interface to a Dallas Semiconductor DS18B20 1-Wire digital thermometer.*/
interface DS18B20 extends key 
{
  /* Set the sampling frequency and resolution.

  The temperature will be sampled every 2**log2Seconds seconds.

  The value will have res binary digits of fraction.
  res must be in the range 1 through 4.

  Temperature changes will not be logged unless they exceed the specified
  hysteresis, which is in units of 1/16 degree Celsius.

  Returns a read-only capability to the Logfile containing records
  of type W1Mult.LogRecord16 
  in which the value field is the temperature in units of 1/16 degree Celsius.
  */
  Logfile configure(unsigned byte log2Seconds, unsigned byte res,
            unsigned short hysteresis);
};
