package capros;

/* This object multiplexes several devices on a 1-Wire network. */
interface W1Mult extends key 
{
  /* A structure for logging records of 16-bit values. */
  struct LogRecord16 {
    Logfile.recordHeader header;
    short value;
    short param;
    unsigned long trailer;
  };

  void registerBus(key NPCap, unsigned long subType);
};
