package capros;

interface Constructor extends key 
{
  key request(SpaceBank bank, key sched, key arg);	// for compatibility
  unsigned long isDiscreet();
  key seal();
  void insertConstituent(unsigned long num, key k);
  void insertPC(unsigned long pc);
  void insertAddrSpace(key space);
  void insertSymtab(key sym);
  void insertKeeper(key keeper);
};

interface ConstructorRequestor extends key {
  /* Individual constructors will inherit from this. */
};
