package capros;

namespace DMA32 {
  /* This type is for DMA addresses
  on architectures where they will fit in 32 bits. */
  typedef unsigned <32> DMAAddress;
  const unsigned short DMAAddressBits = 32;
};

namespace DMA64 {
  /* This type is for DMA addresses
  on architectures where they will fit in 64 bits but not 32. */
  typedef unsigned <64> DMAAddress;
  const unsigned short DMAAddressBits = 64;
};

/** Errno is not an object, just a collection of declarations and functions. */
interface Errno {

  // Exceptions corresponding to Linux error numbers:

  exception Perm;
  exception NoEnt;
  exception Again;
  exception NoMem;
  exception NoDev;
  exception Inval;
  exception NoSpc;
  exception MsgSize;
  exception ConnReset;
  exception Shutdown;
  exception HostUnreach;
  exception Already;

  /** Translate an exception code to a positive error number.
  Returns zero if the exception has no corresponding number. */
  //client unsigned long ExceptionToErrno(unsigned long excep);

  /** Translate a positive error number to an exception code.
  Returns zero if the number has no corresponding exception. */
  //client unsigned long ErrnoToException(unsigned long errno);
};
