#ifndef __PSEUDOREGS_i486_H__
#define __PSEUDOREGS_i486_H__

/* This file is automatically generated and is hereby
   placed in the public domain */




typedef struct pseudoregs pseudoregs_t;
struct pseudoregs {
  uint32_t   invType;
  uint32_t   invKey;
  uint32_t   sndLen;
  uint32_t   sndPtr;
  uint32_t   sndKeys;
  uint32_t   rcvKeys;
  uint32_t   testme;
};


#endif /* __PSEUDOREGS_i486_H__ */
