#ifndef __TRACEREGS_i486_H__
#define __TRACEREGS_i486_H__

/* This file is automatically generated and is hereby
   placed in the public domain */




typedef struct traceregs traceregs_t;
struct traceregs {
  uint64_t   trCycles;
};


#endif /* __TRACEREGS_i486_H__ */
