package capros;

/* The internal capability by which the interrupt handler calls the
main IP thread. */
interface IPInt extends key {
  unsigned long processInterrupt(unsigned long fcn, unsigned long arg);
};
