package capros;

/* The internal capability by which the interrupt handler calls the
main TCP thread. */
interface TCPIPInt extends key {
  void processInterrupt(unsigned long fcn, unsigned long arg);
};
