package capros;

/* Explain This object . */
interface IndexedKeyStore extends key 
{
  exception Exists;	// 
  exception NotFound;	// 
  exception NoSpace;	// 

  const unsigned long maxNameLen = 255;

  // The following are not implemented in IDL because the IDL compiler
  // isn't up to the task.

  client void put(key k,
                  unsigned long nameLen,
                  out unsigned byte name);    // this is a lie, this is
                        // really an input array of bytes.

  client key get(unsigned long nameLen,
                 out unsigned byte name);    // this is a lie, this is
                        // really an input array of bytes.

  client void delete(unsigned long nameLen,
                     out unsigned byte name);    // this is a lie, this is
                        // really an input array of bytes.

  /* Need a way to list all the entries.
     Need permission bits for writing and for listing entries. */
};
