package capros;

namespace DMA32 {
  /* This type is for DMA addresses and physical memory addresses
  on architectures where they will fit in 32 bits. */
  typedef unsigned <32> DMAAddress;
  const unsigned short DMAAddressBits = 32;
};

namespace DMA64 {
  /* This type is for DMA addresses and physical memory addresses
  on architectures where they will fit in 64 bits but not 32. */
  typedef unsigned <64> DMAAddress;
  const unsigned short DMAAddressBits = 64;
};
