package capros;

/* Interface to Forwarder keys.
 */
interface Forwarder extends key {
  /* Flags: */
  const unsigned long sendCap = 2;	// transmit non-opaque key in key[2]
  const unsigned long sendWord = 4;	// transmit word in w3

  capros.key getTarget();
  capros.key swapTarget(capros.key target);

  const unsigned short maxSlot = 1;
  /* These two raise key.RequestError if slot > maxSlot. */
  capros.key getSlot(unsigned short slot);
  capros.key swapSlot(unsigned short slot, capros.key key);

  unsigned long getDataWord();
  unsigned long swapDataWord(unsigned long data);

  void setBlocked();
  void clearBlocked();

  /* Returns an opaque key to the forwarder. */
  /* Raises key.RequestError if flags has bits other than the two above. */
  capros.key getOpaqueForwarder(unsigned long flags);
};
