package capros;

/** Kernel interface to page and GPT keys.
 *
 */
interface Memory extends key {
  /* Restrictions: */
  const unsigned long opaque = 1;
  const unsigned long weak = 2;
  const unsigned long noCall = 4;
  const unsigned long readOnly = 8;

  /* Returns a key to the memory object with reduced permissions. */
  capros.key reduce(unsigned long restrictions);

  /* Returns the memory object's lss and restrictions. */
  void lssAndPerms(out unsigned long lss, out unsigned long restrictions);

  unsigned long getRestrictions();
};
