package eros;

/** Kernel interface to page keys.
 *
 */
interface Page extends Memory
  raises(eros.key.RequestError, eros.key.NoAccess) {

  /* Sets the contents of the page to zero. 
     Raises NoAccess if the key is read only. */
  void zero();

  /* Sets the contents of the page equal to the contents of fromPage.
     Raises NoAccess if the key is read only.
     Raises RequestError if fromPage is not a page key. */
  void clone(eros.key fromPage);
};
