package capros;

/** Interface to allow processes to sleep voluntarily.
 */
interface Sleep extends key {

  /* Returns the time in nanoseconds since some time in the past. 
     FIXME: Is this monotonic over checkpoint/restart? */
  unsigned long long getTimeMonotonic();

  /** Sleep until the specified number of milliseconds has passed */
  void sleep(unsigned long long ms);

  /** Sleep until the specified number of milliseconds from epoch */
  void sleepTill(unsigned long long ms);
};
