package capros;

/** Kernel interface to system control functions.
 *
 */
interface SysTrace extends key {
  void CheckConsistency();

  void clearKernelStats();

  /* Set tracing of invocations on or off. 
  */
  void setInvocationTrace(boolean onOff);
};
