package eros.domain.winsys;

/** 
 * The "master" interface for the window system.  (See "session.idl"
 * for the interface for general window system client domains.)
 */
interface master extends eros.key raises(VideoError) {
  exception VideoError;

  /** General initialization routine for the window system.  Provide a
   *  capability to the bus probe domain so window system can
   *  determine which video hardware is available.
   */
  void initialize(eros.key prober);

  /** The window system provides two session creator keys, one for
   * trusted and one for untrusted sessions.
   *
   */
  void get_session_creators(out eros.key trusted,
                            out eros.key untrusted);

  /**
   * Send a keyboard event to the window system.
   */
  void keybd_event(short scancode);

  /**
   * Send a mouse event to the window system.
   */
  void mouse_event(unsigned long button_mask, short x, short y);

  /**
   * Set the physical screen resolution.
   */
  void set_resolution(unsigned long width, unsigned long height,
		      unsigned long depth);

  /**
   * Query the current screen resolution.
   */
  void get_resolution(out unsigned long width,
		      out unsigned long height,
		      out unsigned long depth);
};

