package capros;

interface NetListener extends key {

  exception NoMem;	// server does not have enough memory for the operation
  exception Already;    // There is already a listener on the socket

  /**
   * Listen - Fork process to listen for connections on socket
   *  
   * @param[in] socket The TCPListenSocket to listen on
   * @param[in] handler A constructor for the process which will handle the
   *            new connection.
   * @exception - TBD
   */
  void listen(TCPListenSocket socket, ConstructorRequestor handler);

  /**
   * Stop - Stop listening to the socket
   *
   * @exception NotListening if the listener isn't currently listening.
   */
  void stop();

  /* NetListener obeys key.destroy().
     This releases the reserved local port and other resources. */
  /* NetListener obeys key.getType(). */
};
