package capros;

/* Explain This object . */
interface SWCA extends key 
{
  exception noInverter;	// the specified inverter does not exist
  exception noData;	// no data are available yet

  /* Get the latest data from the specified inverter.
  inverterNum is zero-based. */
  void getInvChgAmps(unsigned byte inverterNum,
                   out unsigned short amps, out RTC.time_t time);
  void getLoadAmps(unsigned byte inverterNum,
                   out unsigned short amps, out RTC.time_t time);
};

// Interface for internal use only:
interface SWCANotify extends key
{
  void notify();
};
